version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: chatty_db
    restart: always
    ports:
      - '${DATABASE_PORT:-3306}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  web:
    build: .
    container_name: chatty_web
    restart: always
    ports:
      - '${APP_PORT:-3000}:3000'
    depends_on:
      - db
    volumes:
      - .:/rails
    environment:
      DATABASE_URL: '${DATABASE_URL}'

volumes:
  mysql_data:
  redis_data:
