:concurrency: 5
:scheduler:
  :schedule:
    update_application_chat_count_job:
      every: '1h'
      class: 'UpdateApplicationChatCountJob'
      queue: default
    
    update_chat_messages_count_job:
      every: '1h'
      class: 'UpdateChatMessagesCountJob'
      queue: default

production:
  :concurrency: 10

development:
  :concurrency: 5
